const Paths = {
  main: {
    path: '/',
    title: 'Main',
  },
  about: {
    path: '/about',
    title: 'About Us',
  },
  error: {
    path: '*',
    title: 'Error',
  },
  critiques: {
    path: '/critiques',
    title: 'Critiques',
  },
};

const Buttons = {
  search: 'SEARCH',
};

const Content = {
  rating: 'Rating: ',
  greeting: 'Enter the movie you are looking for, search by any characteristics.',
  about:
    "MovieSearch is a unique movie search platform. Here you'll find a movie or cartoon for every taste. We take care of adding new releases as soon as they are released. Use our search to find a movie to enjoy tonight.",
  critiquesTitle: 'Here you can leave your review and read the reviews of other users.',
  formTitle: 'Leave a review: ',
  critique: {
    nameLabel: "You'r full name: ",
    dateLabel: 'Date viewed: ',
    movieLabel: 'Movie title: ',
    reviewLabel: "You'r review: ",
    recommend: 'recommend',
    unrecommended: "don't recommend",
    personalDate: 'I consent to my personal data field',
    country: 'Country of residence: ',
    photo: 'Profile picture: ',
    cardMovie: 'Movie: ',
    cardRecommended: 'Recommends for viewing: ',
    cardDate: 'Viewing date: ',
    cardReview: 'Review: ',
    recommendedMovie: 'yes',
    unrecommendedMovie: 'no',
  },
  formSubmit: 'Send a review',
};

const InputName = {
  name: 'name',
  country: 'country',
  photo: 'photo',
  movie: 'movie',
  date: 'date',
  review: 'review',
  personalDate: 'personal',
};

const ImageFormats = '.jpg,.jpeg,.png';

const Pages = {
  main: 'Main',
  about: 'About Us',
  error: '404 Page not found',
  critiques: 'Critiques',
};

const LocalStorageKeys = {
  search: 'search',
};

const Countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bangladesh',
  'Barbados',
  'Bahamas',
  'Bahrain',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burma',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo-Brazzaville',
  'Congo-Kinshasa',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cura?ao',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'El Salvador',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Federated States of Micronesia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Lands',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard and McDonald Islands',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'R?union',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barth?lemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent',
  'Samoa',
  'San Marino',
  'S?o Tom? and Pr?ncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Swaziland',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Vietnam',
  'Venezuela',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

const ErrorMessages = {
  emptyLine: 'The field cannot be empty',
  invalidName: 'You need two words starting with a capital letter, at least 4 characters',
  missingPhoto: 'Missing photo',
  wrongDate: 'It is not possible to choose a date longer than today',
  recommended: 'It is necessary to leave recommendations',
  personalData: 'You must consent to the processing of personal data',
};

const RegName = /^([A-Z А-Я][a-zа-я]{2,})[ ]([A-Z А-Я][a-zа-я]{2,})(([A-Z А-Я][a-zа-я]{0,}){0,})/gm;

export {
  Paths,
  Buttons,
  Content,
  InputName,
  Pages,
  LocalStorageKeys,
  Countries,
  ErrorMessages,
  RegName,
  ImageFormats,
};
